---
galaxy_info:
  author: Ivan Vinogradov <vinogradovia@gmail.com>
  description: configure fail2ban from web ui
  license: WTFPL
  min_ansible_version: "2.2"
  galaxy_tags:
    - fail2ban
dependencies:
  - role: docker
    when: fail2ban_ui_orchestrator == 'docker'
