---
galaxy_info:
  author: Ivan Vinogradov <vinogradovia@gmail.com>
  description: install and configure Fail2Ban (jails, filters)
  license: WTFPL
  min_ansible_version: "2.2"
  galaxy_tags:
    - fail2ban
    - security
dependencies: []
