---
- name: Initialize all resources
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Initializing resource
      ansible.builtin.copy:
        dest: "{{ tmp_dir }}{{ item }}_created.yml"
        content: |
          {{ hostvars[item] }}
      loop: "{{ groups['monitoring_servers'] }}"

- name: Ensure resource creation
  hosts: test_resources
  gather_facts: false
  tasks:
    - name: Resource initialized
      ansible.builtin.stat:
        path: "{{ tmp_dir }}{{ inventory_hostname }}_created.yml"
      register: result
      failed_when: not result.stat.exists
