---
# defaults file for infra_dns

infra_dns_packages:
  - bind9
  - bind9-utils

infra_dns_zone_name: in.moon.ru
infra_dns_zone_dir: /etc/bind/master

infra_dns_listen_on:
  # - any
  - 10.20.30.240
  # - 127.0.0.1

infra_dns_listen_on_v6:
  - none

infra_dns_allow_query:
  - 10.20.30.0/24
  - 10.20.31.0/24

infra_dns_allow_transfer:
  - none

infra_dns_forwarders:
  - 8.8.8.8
  - 8.8.4.4

infra_dns_recursion: true

infra_dns_allow_recursion:
  - "{{ infra_dns_allow_query }}"

infra_dns_dnssec_validation: auto

infra_dns_zone_ttl: 600

infra_dns_soa_ns: "dns.{{ infra_dns_zone_name }}"
infra_dns_soa_contact: "hostmaster.{{ infra_dns_zone_name }}"
infra_dns_soa_refresh: 3H
infra_dns_soa_retry: 15M
infra_dns_soa_expire: 2W
infra_dns_soa_minimum: 10M

infra_dns_zone_ns_records:
  - "dns.{{ infra_dns_zone_name }}."

infra_dns_zone_records: []

infra_dns_zone_include_hosts: true
