{
 "title": "9108-9109 - NGINX",
 "description": "Prometheus Nginx exporter metrics.",
 "tags": [
  "prometheus",
  "nginx_exporter"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "database", "label": "database", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(nginx_up, instance)"
   },
   {
    "name": "logs",
    "query": "label_values(nginx_http_response_time_seconds{instance=~\"$instance.*\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "NGINX Status for $instance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nginx_connections_active{instance=~\"$instance.*\"}",
     "legendFormat": "{{instance}} active"
    },
    {
     "expr": "nginx_connections_reading{instance=~\"$instance.*\"}",
     "legendFormat": "{{instance}} reading"
    },
    {
     "expr": "nginx_connections_waiting{instance=~\"$instance.*\"}",
     "legendFormat": "{{instance}} waiting"
    },
    {
     "expr": "nginx_connections_writing{instance=~\"$instance.*\"}",
     "legendFormat": "{{instance}} writing"
    }
   ]
  },
  {
   "title": "Processed connections",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted{instance=~\"$instance.*\"}[5m])",
     "legendFormat": "{{instance}} accepted"
    },
    {
     "expr": "irate(nginx_connections_handled{instance=~\"$instance.*\"}[5m])",
     "legendFormat": "{{instance}} handled"
    }
   ]
  },
  {
   "title": "Status codes per second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_count_total{instance=~\"$instance.*\"}[1m])) by (status) != 0",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total{instance=~\"$instance.*\"}[5m])",
     "legendFormat": "{{instance}} total requests"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_time_seconds_count{instance=~\"$instance.*\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_time_seconds_sum{instance=~\"$instance.*\"}[5m])) by (instance) / sum(rate(nginx_http_response_time_seconds_count{instance=~\"$instance.*\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Response time (90% quantile)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "nginx_http_response_time_seconds{instance=~\"$instance.*\",quantile=\"0.9\",method=\"GET\",status=~\"2[0-9]*\"}",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "HTTP Traffic",
   "type": "timeseries",
   "description": "Response sizes in bytes",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_size_bytes{instance=~\"$instance.*\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}