---
postgresql_replication_role: read_replica
postgresql_replication_node_id: 2
postgresql_replication_primary_host: 192.168.58.10
postgresql_replication_repl_password: molecule-test-repl-password
postgresql_replication_repmgr_password: molecule-test-repmgr-password
