---
galaxy_info:
  author: Ivan Vinogradov <vinogradovia@gmail.com>
  description: configure monitoring stack agent
  license: WTFPL
  min_ansible_version: "2.2"
  galaxy_tags:
    - monitoring
dependencies:
  - role: docker
    when: monitoring_agent_orchestrator == 'docker'
    vars:
      docker_daemon_json_options: "{{ monitoring_agent_docker_daemon_json_options }}"
