groups:

- name: BaseAlerts


  rules:
    - alert: HighCpuUsage
      expr: |
        (
          rate(process_cpu_seconds_total{job=~"$job", instance=~"$instance"}[15m])
          /
          machine_cpu_cores{job=~"$job", instance=~"$instance"}
        ) * 100 > 80
      for: 15m
      labels:
        severity: critical
      annotations:
        summary: HighCPUUsage (instance {{ $labels.instance }})
        description: "HighCPUUsage {{ $labels.instance }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
