---
mysql_replication_role: dr_replica
mysql_replication_server_id: 3

mysql_replication_primary_host: 10.66.6.21
mysql_replication_repl_password: "demo-mysql-repl-pwd-CHANGEME"

monitoring_agent_mysqld_exporter_enabled: true
monitoring_agent_mysqld_exporter_password: "demo-mysqld-exporter-password-CHANGE-ME"
