apiVersion: v1
entries:
  universal-chart:
  - apiVersion: v2
    created: "2026-02-15T03:52:44.996625255+03:00"
    description: Nixys universal Helm chart for deploy your apps to Kubernetes
    digest: 2ba90b798a78bbfe03cae74c5e8210e680f155cead2fe61735348c2006ae6be7
    maintainers:
    - email: r.andreev@nixys.io
      name: Roman Andreev
    - email: a.zhideev@nixys.io
      name: Anton Zhideev
    - email: evg.krsk@gmail.com
      name: Evgenii Tereshkov
    - email: s@lavr.me
      name: Sergey Lavrinenko
    - email: v.sokhan@nixys.io
      name: Viktor Sokhan
    - email: gromrx1@gmail.com
      name: Ruslan Gainanov
    - email: a.danielyan@nixys.io
      name: Artem Danielyan
    - email: r.emelyanov@nixys.io
      name: Roman Emelyanov
    name: universal-chart
    urls:
    - universal-chart-2.8.1.tgz
    version: 2.8.1
generated: "2026-02-15T03:52:44.992402844+03:00"
